version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs
    network_mode: host
    command: daemon 
  ganache:
    image: trufflesuite/ganache-cli
    network_mode: host
  apocryph-dao:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    network_mode: host